APP/forms/userForms.py
#-*- coding: utf-8 -*-
# @Time    : 2018/9/13 0013 17:25
# @Author  : zhyipeng
# @File    : userForms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, Email, ValidationError
from flask_wtf.file import FileAllowed, FileRequired, FileField
from APP.models import Users

ALLOW_PHOTOS = ['jpg', 'png', 'jpeg', 'bmp']

class UserRegisterForm(FlaskForm):
    '''
    用户注册表单，用户名，密码，重复密码，邮箱，验证码，头像
    '''

    username = StringField(label='用户名', validators=[DataRequired(message='用户名不能为空')])
    password = PasswordField(label='密码', validators=[DataRequired(message='密码不能为空'),
                                                     Length(min=6, max=18, message='请输入6-18位密码')])
    re_password = PasswordField(label='确认密码', validators=[DataRequired(message='请确认密码'),
                                                          EqualTo('password', message='两次密码不一致')])
    email = StringField(label='邮箱', validators=[DataRequired(message='邮箱不能为空'),
                                                Email(message='邮箱格式不正确')])
    code = StringField(label='验证码', validators=[DataRequired(message='请输入验证码')])
    photo = FileField(label='头像', validators=[FileRequired(message='请选择要上传的文件'),
                                              FileAllowed(ALLOW_PHOTOS, message='无法识别的图片格式')])
    submit = SubmitField(label='注册')

    def validate_username(self, field):
        '''
        判断用户是否存在
        :param field: 字段
        :return: bool
        '''
        user = Users.query.filter_by(username=field.data).first()
        if user:
            raise ValidationError(message='该用户名已被注册')

    def validate_email(self, field):
        '''
        判断邮箱是否存在
        :param field: 字段
        :return: bool
        '''
        user = Users.query.filter_by(email=field.data).first()
        if user:
            raise ValidationError(message='该邮箱已被注册')




class UserLoginForm(FlaskForm):
    '''
    用户登录表单，用户名，密码，验证码
    '''

    username = StringField(label='用户名', validators=[DataRequired(message='用户名不能为空')])
    password = PasswordField(label='密码', validators=[DataRequired(message='密码不能为空')])
    code = StringField(label='验证码', validators=[DataRequired(message='请输入验证码')])
    submit = SubmitField(label='登录')

    def validate_username(self, field):
        '''
        判断用户是否存在
        :param field: 字段
        :return: bool
        '''
        user = Users.query.filter_by(username=field.data).first()
        if not user:
            raise ValidationError(message='该用户名不存在')

APP/views/user.py
# -*- coding: utf-8 -*-
# @Time    : 2018/9/13 0013 17:06
# @Author  : zhyipeng
# @File    : userModel.py
import os
import time
import uuid

from flask import Blueprint, render_template, redirect, url_for, make_response, flash, request, current_app
from APP.forms import UserRegisterForm, UserLoginForm
from APP.extensions import photos, db
from PIL import Image, ImageFont, ImageFilter, ImageDraw
import random
from io import BytesIO
from APP.models import Users
# from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import logout_user, login_user, login_required
from APP.email import send_mail

user = Blueprint('user', __name__)
code_str = ''

'''
@user.route('/index/')
def user_index():
    username = request.cookies.get('username')
    photo = request.cookies.get('photo')

    return render_template('user/index.html', username=username, photo=photo)
'''

@user.route('/index/')
def user_index():
    return render_template('user/index.html')

'''
@user.route('/logout/')
def user_logout():
    resp = redirect(url_for('user.user_index'))
    resp.delete_cookie('username')
    resp.delete_cookie('photo')
    return resp
'''

@user.route('/logout/')
def user_logout():
    logout_user()
    return redirect(url_for('user.user_index'))

'''
@user.route('/login/', methods=['GET', 'POST'])
def user_login():

    form = UserLoginForm()
    if form.validate_on_submit():
        code = form.code.data
        global code_str
        if code.lower() == code_str.lower():
            username = form.username.data
            password = form.password.data
            users = Users.query.filter(Users.username == username).first()
            if users:
                if check_password_hash(users.password, password):
                    # 登录匹配
                    resp = redirect(url_for("user.user_index"))
                    resp.set_cookie("username", username)
                    resp.set_cookie("photo", users.photo)

                    return resp
                else:
                    flash("用户名或密码错误")
            else:
                flash("用户名或密码错误")
    return render_template('user/login.html', form=form)
'''


@user.route('/login/', methods=['GET', 'POST'])
def user_login():
    form = UserLoginForm()
    if form.validate_on_submit():
        code = form.code.data
        global code_str
        if code.lower() == code_str.lower():
            username = form.username.data
            password = form.password.data
            users = Users.query.filter(Users.username == username).first()
            if users:
                if users.check_password(password):
                    # 登录匹配，保存用户
                    login_user(users)

                    resp = redirect(url_for("user.user_index"))
                    return resp
                else:
                    flash("用户名或密码错误")
            else:
                flash("用户名或密码错误")
    return render_template('user/login.html', form=form)

'''
@user.route('/register/', methods=['GET', 'POST'])
def user_register():

    form = UserRegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        photo = form.photo.data
        code = form.code.data
        email = form.email.data

        # 验证通过
        global code_str
        if code.lower() == code_str.lower():
            users = Users.query.filter(Users.username == username).first()
            users_for_email = Users.query.filter(Users.email == email).first()
            if users is None:
                if users_for_email is None:
                    # 保存头像
                    suffix = os.path.splitext(photo.filename)[1]
                    affix = str(uuid.uuid4())
                    new_filename = affix + suffix
                    photos.save(photo, name=new_filename)
                    # 压缩
                    img_path = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], new_filename)
                    img = Image.open(img_path)
                    img.thumbnail((64, 64))
                    img.save(img_path)

                    # 保存到数据库
                    new_user = Users()
                    new_user.username = username
                    new_user.password = generate_password_hash(password)
                    new_user.photo = new_filename
                    new_user.email = email
                    db.session.add(new_user)

                    # 设置cookie
                    resp = redirect(url_for('user.user_index'))
                    resp.set_cookie('username', username)
                    resp.set_cookie('photo', new_filename)

                    return resp
                else:
                    flash('该邮箱已注册')
            else:
                flash('用户名已存在')
        else:
            flash('验证码错误')

    return render_template('user/register.html', form=form)
'''

@user.route('/register/', methods=['GET', 'POST'])
def user_register():

    form = UserRegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        photo = form.photo.data
        code = form.code.data
        email = form.email.data

        # 验证通过
        global code_str
        if code.lower() == code_str.lower():
            user = Users(username=username, password=password, email=email)
            suffix = os.path.splitext(photo.filename)[1]
            affix = str(uuid.uuid4())
            new_filename = affix + suffix
            photos.save(photo, name=new_filename)
            # 压缩
            img_path = os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], new_filename)
            img = Image.open(img_path)
            img.thumbnail((64, 64))
            img.save(img_path)

            user.photo = new_filename

            db.session.add(user)
            db.session.commit()

            token = user.generate_token()
            # 发送激活邮件
            send_mail(subject='用户激活',
                      recipients=[email],
                      email_temp='active',
                      username=username,
                      token=token
                      )
            flash('激活邮件已发送至您的邮箱，请点击邮件中的链接已完成激活')

        else:
            flash('验证码错误')

    return render_template('user/register.html', form=form)

@user.route('/active/<token>')
def user_active(token):
    '''
    激活链接
    :param token: 会话
    :return:
    '''
    if Users.user_active(token):
        flash('激活成功，即将跳转登录界面')
        time.sleep(2)
        return redirect(url_for('user.user_login'))
    else:
        return '激活失败'


@user.route('/get_code/')
def get_code():
    '''
    验证码
    :return:
    '''
    # 生成验证吗
    global code_str
    im, code_str = validate_picture()

    buf = BytesIO()
    im.save(buf, 'jpeg')
    buf_byte = buf.getvalue()

    resp = make_response(buf_byte)

    resp.headers['Content-Type'] = 'image/jpeg'

    return resp


# 生成验证码
def validate_picture():
    '''
    生成验证码
    :return: im: Image对象; str: 验证码
    '''
    total = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345789'
    # 图片大小
    width = 130
    height = 50
    # 先生成一个图片对象
    im = Image.new('RGB', (width, height), 'white')
    # 设置字体
    font = ImageFont.truetype('simsun', 40)
    # 创建一个draw对象
    draw = ImageDraw.Draw(im)
    str = ''
    # 输出每一个文字
    for item in range(4):
        text = random.choice(total)
        str += text
        draw.text((6 + random.randint(4, 7) + 20 * item, 5 + random.randint(3, 7)), text=text, fill='black', font=font)

        # 划几根干扰线
    for num in range(4):
        x1 = random.randint(0, width / 2)
        y1 = random.randint(0, height / 2)
        x2 = random.randint(0, width)
        y2 = random.randint(height / 2, height)
        draw.line(((x1, y1), (x2, y2)), fill='black', width=1)

        # 模糊下,加个帅帅的滤镜～
    im = im.filter(ImageFilter.FIND_EDGES)
    return im, str

APP/templates/user/index.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
    {{ super() }}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <style>
        .photo {
            height: 32px;
            width: 32px;
            border-radius: 50%;
            overflow: hidden;
            float: left;
            margin-right: 10px;
        }
    .quit-button{
        {#float: right;#}
        font-size: 16px;
    }

    </style>
{% endblock %}


{% block content %}
    <div class="container">

        <!-- The justified navigation menu is meant for single line per list item.
             Multiple lines will require custom code not provided by Bootstrap. -->
        <div class="masthead">
            {% if current_user.is_authenticated %}
                <div class="photo"><img
                        src="{{ url_for('static', filename='image/') }}{{ current_user.photo }}"></div>
                <h3 class="text-muted" style="line-height: 32px;" >
                    {{ current_user.username }}
                    <a class="quit-button" href="{{ url_for('user.user_logout') }}">注销</a>
                </h3>

            {% else %}
                <h3 class="text-muted">
                    <span>您好！请</span>
                    <a href="{{ url_for('user.user_login') }}">登录</a>
                    <span>|</span>
                    <a href="{{ url_for('user.user_register') }}">注册</a>
                </h3>
            {% endif %}
            <nav>
                <ul class="nav nav-justified">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">Services</a></li>
                    <li><a href="#">Downloads</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </nav>
        </div>

        <!-- Jumbotron -->
        <div class="jumbotron">
            <h1>Marketing stuff!</h1>
            <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus
                commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
            <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p>
        </div>

        <!-- Example row of columns -->
        <div class="row">
            <div class="col-lg-4">
                <h2>Safari bug warning!</h2>
                <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally
                    causes rendering errors in the justified nav that are cleared upon refreshing.</p>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula
                    porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                    ut fermentum massa.</p>
                <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>

        <!-- Site footer -->
        <footer class="footer">
            <p>&copy; 2016 Company, Inc.</p>
        </footer>

    </div> <!-- /container -->
{% endblock %}

APP/templates/user/login.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
    {{ super() }}
    <style>
        #submit {
            display: block;
            {#margin: 0 auto;#}
            position: relative;
            left: 80px;
        }
        #register{
            display: block;
            position: absolute;
            right: 80px;
            bottom: 0;
        }

        #code {
            width: 65%;
        }

        #code-img {
            position: absolute;
            right: 3%;
            top: 220px;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="col-md-4 col-md-offset-4" style="position: relative;">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <strong>Warning!</strong>{{ message }}
            </div>
        {% endfor %}
        <h2 align="center" class="text-muted">登录</h2>
        {{ wtf.quick_form(form) }}
        <img id="code-img" src="{{ url_for('user.get_code') }}" alt=""
             onclick="this.src='{{ url_for('user.get_code') }}?'+Math.random()">
        <a id="register" class="btn btn-default" href="{{ url_for('user.user_register') }}">注册</a>
    </div>
{% endblock %}

APP/templates/user/register.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
    {{ super() }}
    <style>
        #submit {
            display: block;
            margin: 0 auto;
        }

        #code {
            width: 65%;
        }

        #code-img {
            position: absolute;
            right: 3%;
            top: 375px;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="col-md-4 col-md-offset-4" style="position: relative;">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <strong>Warning!</strong>{{ message }}
            </div>
        {% endfor %}
        <h2 align="center" class="text-muted">注册</h2>
        {{ wtf.quick_form(form) }}
        <img id="code-img" src="{{ url_for('user.get_code') }}" alt=""
             onclick="this.src='{{ url_for('user.get_code') }}?'+Math.random()">
    </div>
{% endblock %}